Expose filter options when creating a persistent subscription.
EventStore/EventStoreDB-Client-Java pull request #122
Opened 2021-12-15 16:59 UTC by YoEight

2021-12-21 13:14 UTC, oskardudycz commented on db-client-java/src/main/java/com/eventstore/dbclient/SubscriptionFilter.java
> +    void addToWirePersistentReadReq(Persistent.CreateReq.AllOptions.Builder builder) {
**SUGGESTION:** It might be worth aligning at least part of the logic with the regular subscription processing, as it's almost the same.

2021-12-21 13:14 UTC, oskardudycz commented
There are no tests checking the filtering feature.

2021-12-21 13:16 UTC, oskardudycz requested changes
I could approve it if it was the single blocker, but I think that we should add at least basic test coverage for the feature.

2022-01-04 13:26 UTC, oskardudycz approved these changes

2022-01-04 15:11 UTC, pvanbuijtene approved these changes

2022-01-04 18:54 UTC, merged