Issue 151: Fix connection attempts
EventStore/EventStoreDB-Client-Java pull request #152
Opened 2022-06-06 09:57 UTC by dpasek-senacor

See: https://github.com/EventStore/EventStoreDB-Client-Java/issues/151

Fixes the retry behavior on connecting to EventStoreDB server, in case the server features could not be retrieved, as server is currently unavailble.

2022-06-06 10:04 UTC, dpasek-senacor commented on db-client-java/src/main/java/com/eventstore/dbclient/GrpcClient.java
> +            if (doConnect() && loadServerFeatures()) {
Both steps must be successful for initializing the client, otherwise the retry loop will be used.

2022-06-07 09:55 UTC, YoEight requested changes
Thanks, @dpasek-senacor for your contribution.

I think a better approach would be to decide whether the server features retrieval process is retriable or not. Whatever exception you got when your ESDB server is not ready/up is a valid case for retrying or moving to the next candidate.

2022-06-07 13:31 UTC, dpasek-senacor commented
> I think a better approach would be to decide whether the server features retrieval process is retriable or not. Whatever exception you got when your ESDB server is not ready/up is a valid case for retrying or moving to the next candidate.

Hi @YoEight ! I have adapted the PR to take the type of exception into account on fetching the server features. This will now throw a `RetryableException` if a retry should be performed otherwise the client is shutdown as before.

I don't know if this is what you meant, but now only a `TimeoutException` or Status `UNAVAIBLE` will trigger the retry.

2022-06-09 11:06 UTC, YoEight approved these changes

2022-06-14 11:30 UTC, ylorph approved these changes

2022-06-14 12:21 UTC, merged