Add equals() and hashCode() to SpecificExpectedRevision
EventStore/EventStoreDB-Client-Java pull request #98
Opened 2021-09-02 11:49 UTC by dpasek-senacor

Add `equals()` and `hashCode()` to SpecificExpectedRevision class to allow quality checks.

These methods are missing and therefore it is not possible to properly check the equality of two `ExpectedRevision` instances.
Adding proper `equals()` implementation is helpful for implementing logic and tests regarding the expected revisions.

2021-09-02 13:25 UTC, YoEight requested changes
Thanks for your contribution!

It looks good but I think you can also implement `equals` and `hashCode` for all `ExpectedRevision` sub-classes too.

2021-09-02 13:31 UTC, dpasek-senacor commented
@YoEight Thanks for your quick review.

The reason why I skipped the implementation of `equals()` and `hashCode()` on the other subclasses was them being singletons. The constructors are package private and therefore a client is not able to create new instances. A client can only use the singleton instances providing instance equality. 

But you are right: for the internal code of the client it would be helpful to be on the safe side and have alle concrete subsclasses to implement equals() / hashCode().

2021-09-03 10:57 UTC, YoEight approved these changes

2021-09-03 11:35 UTC, oskardudycz approved these changes

2021-09-03 13:30 UTC, YoEight commented
Great work!

2021-09-03 13:30 UTC, merged